#!/bin/bash

echo "🌟 Cloudflare Tunnel セットアップガイド 🌟"
echo ""
echo "1. Cloudflare アカウントにログインして以下を実行:"
echo ""
echo "# Cloudflare Tunnel を作成"
echo "cloudflared tunnel create receipt-print-service"
echo ""
echo "2. 作成されたトンネルの credentials.json ファイルを以下にコピー:"
echo "cp ~/.cloudflared/<tunnel-id>.json ./cloudflared-credentials.json"
echo ""
echo "3. cloudflared.yml の hostname を編集:"
echo "- hostname: your-domain.com に変更"
echo ""
echo "4. DNS レコードを追加:"
echo "cloudflared tunnel route dns receipt-print-service your-domain.com"
echo ""
echo "5. Docker Compose で起動:"
echo "docker-compose up -d"
echo ""
echo "📱 これでスマホからも https://your-domain.com でアクセス可能！"
echo ""
echo "🔧 トラブルシューティング:"
echo "- credentials ファイルのパス確認"
echo "- DNS 設定の反映待ち (数分)"
echo "- Cloudflare ダッシュボードでトンネルの状態確認"