#!/bin/bash

echo "🌟 Cloudflare Tunnel セットアップガイド 🌟"
echo ""
echo "1. Cloudflare アカウントにログインして以下を実行:"
echo ""
echo "# Cloudflare Tunnel を作成"
echo "cloudflared tunnel create receipt-print-service"
echo ""
echo "2. Cloudflare ダッシュボードでトンネルトークンを取得:"
echo "- https://one.dash.cloudflare.com/ にアクセス"
echo "- Zero Trust > Access > Tunnels > [your-tunnel] > Configure"
echo "- Public Hostname を設定 (hostname: your-domain.com, service: http://localhost:3000)"
echo "- トークンをコピー"
echo ""
echo "3. .env ファイルにトークンを設定:"
echo "echo 'CLOUDFLARE_TUNNEL_TOKEN=your_token_here' >> .env"
echo ""
echo "4. DNS レコードを追加 (自動で作成される場合もあります):"
echo "cloudflared tunnel route dns <tunnel-id> your-domain.com"
echo ""
echo "5. Docker Compose で起動:"
echo "docker-compose up -d"
echo ""
echo "📱 これでスマホからも https://your-domain.com でアクセス可能！"
echo ""
echo "🔧 トラブルシューティング:"
echo "- credentials ファイルのパス確認"
echo "- DNS 設定の反映待ち (数分)"
echo "- Cloudflare ダッシュボードでトンネルの状態確認"